cropper/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cropper'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo_django_task/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls, name="admin "),
    path("", IndexView.as_view(), name="index"),
    path("feedbacker/", include("feedbacker.urls"), name="feedbacker"),
]

feedbacker/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'feedbacker'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("features", views.FeaturesView.as_view(), name='features'),
    path("features/add", views.FeatureCreateView.as_view(), name='feature_create'),
    path("features/edit/<int:pk>", views.FeatureEditView.as_view(), name='feature_edit'),
    path("features/delete/<int:pk>", views.FeatureDeleteView.as_view(), name='feature_delete'),
    path("tags", views.TagsView.as_view(), name='tags'),
    path("tags/add", views.TagCreateView.as_view(), name='tag_create'),
    path("tags/edit/<int:pk>", views.TagEditView.as_view(), name='tag_edit'),
    path("tags/delete/<int:pk>", views.TagDeleteView.as_view(), name='tag_delete'),
    path("users", views.UsersView.as_view(), name='users'),
    path("users/add", views.UserCreateView.as_view(), name='user_create'),
    path("users/edit/<int:pk>", views.UserEditView.as_view(), name='user_edit'),
    path("users/delete/<int:pk>", views.UserDeleteView.as_view(), name='user_delete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cropper/models.py
from django.db import models

# Create your models here.

feedbacker/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Feature(models.Model):
    name = models.CharField(max_length=80, unique=True)
    description = models.TextField(default="")
    def get_absolute_url(self):
        return reverse('feedbacker:feature_edit', kwargs={'pk': self.id})


class Tag(models.Model):
    name = models.CharField(max_length=80, unique=True)


class User(models.Model):
    name = models.CharField(max_length=80, unique=True)


class Project(models.Model):
    name = models.CharField(max_length=80, unique=True)
    description = models.TextField()
    url = models.URLField()

feedbacker/forms.py
from __future__ import annotations

from django import forms
from feedbacker import models


class FeatureCreateForm(forms.ModelForm):
    class Meta:
        model = models.Feature
        fields = ['name', 'description']


class TagCreateForm(forms.ModelForm):
    class Meta:
        model = models.Tag
        fields = ['name']


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ['name']

cropper/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class IndexView(TemplateView):
    template_name = 'cropper/index.html'
    #def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
    #    context['message'] = 'Hello World'
    #    return context
    #pass

demo_django_task/views.py
from django.views.generic import TemplateView
from feedbacker.models import Project

class IndexView(TemplateView):
    template_name = "demo_django_task/projects.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        return context

feedbacker/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, View, UpdateView
from feedbacker.models import Feature, Tag, User
from feedbacker.forms import FeatureCreateForm, TagCreateForm, UserCreateForm
from django.http import HttpResponse
from django.views.generic.edit import DeleteView

# Create your views here.
categories = ('features', 'tags', 'users')


class IndexView(TemplateView):
    template_name = "feedbacker/index.html"
    extra_context = {'categories': categories}


class FeaturesView(ListView):
    template_name = "feedbacker/features.html"
    model = Feature
    extra_context = {'categories': categories, 'category': 'features'}

class FeatureCreateView(View):
    model = Feature
    def post(self, request):
        form = FeatureCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Created<script>delayedClose()</script>")
        else:
            return HttpResponse("Invalid name", status=200, reason="Invalid name reason")


class FeatureEditView(UpdateView):
    model = Feature
    fields = ['name', 'description']
    success_url = "/feedbacker/features"
    template_name = "feedbacker/edit_form.html"


class FeatureDeleteView(DeleteView):
    # specify the model you want to use
    model = Feature
    template_name = "feedbacker/confirm_delete.html"
    extra_context = {'categories': categories, 'category': 'features', 'entity': 'feature'}
    # can specify success url
    # url to redirect after successfully deleting object
    success_url = "/feedbacker/features"


class TagsView(ListView):
    template_name = "feedbacker/tags.html"
    extra_context = {'categories': categories, 'category': 'tags'}
    model = Tag


class TagCreateView(View):
    model = Tag
    def post(self, request):
        form = TagCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Created<script>delayedClose()</script>")
        else:
            return HttpResponse("Invalid name", status=200, reason="Invalid name reason")


class TagEditView(UpdateView):
    model = Tag
    fields = ['name']
    success_url = "/feedbacker/tags"
    template_name = "feedbacker/edit_form.html"


class TagDeleteView(DeleteView):
    # specify the model you want to use
    model = Tag
    extra_context = {'categories': categories, 'category': 'tags', 'entity': 'tag'}
    template_name = "feedbacker/confirm_delete.html"
    success_url = "/feedbacker/tags"


class UsersView(ListView):
    template_name = "feedbacker/users.html"
    extra_context = {'categories': categories, 'category': 'users'}
    model = User

class UserCreateView(View):
    model = User
    def post(self, request):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Created<script>delayedClose()</script>")
        else:
            return HttpResponse("Invalid name", status=200, reason="Invalid name reason")


class UserEditView(UpdateView):
    model = User
    fields = ['name']
    success_url = "/feedbacker/users"
    template_name = "feedbacker/edit_form.html"


class UserDeleteView(DeleteView):
    # specify the model you want to use
    model = User
    extra_context = {'categories': categories, 'category': 'users', 'entity': 'user'}
    template_name = "feedbacker/confirm_delete.html"
    success_url = "/feedbacker/users"

cropper/templates/cropper/index.html
{% extends "demo_django_task/base.html" %}
{% load static i18n bootstrap5 %}
{% block content %}
        <h1>Color replacer</h1>
    <table>
        <tbody>
            <tr>
                <td><label for="image_file">Image file:</label></td>
                <td colspan="2"><input type="file" id="image_file" name="image_file" accept="image/png, image/gif, image/jpeg" /></td>
            </tr>
            <tr>
                <td><label for="old_color">Old color:</label></td>
                <td><input type="color" id="old_color" name="old_color" value="#FFFFFF" /></td>
                <td><button id="apply_metal">Apply metal</button><input type="file" id="metal_image_file" name="metal_image_file" accept="image/png, image/gif, image/jpeg" /></td>
            </tr>
            <tr>
                <td><label for="new_color">New color:</label></td>
                <td><input type="color" id="new_color" name="new_color" value="#e66465" /></td>
                <td><button id="undo">Undo</button></td>
            </tr>
            <tr>
                <td><label for="tolerance">Color tolerance:</label></td>
                <td><input type="number" id="tolerance" name="tolerance" value="30" max="767"/></td>
                <td><button id="change_colors">Change colors</button></td>
            </tr>
            <tr>
                <td><label for="tolerance">Max # of colors in the palette:</label></td>
                <td><input type="number" id="max_colors_palette" name="max_colors_palette" value="8" max="767"/></td>
                <td><button id="recreate_palette">Recreate palette</button></td>
            </tr>
            <tr>
                <td><label for="clip">Cropping style</label></td>
                <td><select id="clip">
                    <option value="resize-left-top" selected>Resize</option>
                    <option value="--">--</option>
                    <option value="trim">trim</option>
                </select></td>
                <td><button id="download">Download</button></td>
            </tr>
        </tbody>
    </table>
    <div id="palette_container">
        Palette:
        <div id="palette"></div>
    </div>
    <div id="container"></div>
    <canvas id="metal_canvas"></canvas>

{% endblock %}
{% block scripts %}
    {{ block.super }}
    <!--script src="https://unpkg.com/konva@9/konva.min.js"></script-->
    <script src="{% static 'js/konva.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/color_editor.js' %}"></script>
{% endblock %}

feedbacker/templates/feedbacker/base.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# Load the tag library #}
    {% load i18n %}
    {% load static %}
    {% load bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sidebars.css' %}" />
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <script src="https://kit.fontawesome.com/666340fc51.js" crossorigin="anonymous"></script>

    <div>
        <!--div class="content" id="content"-->
            <!--div id="" class=""-->
                {% block content %}
                    <h1 class="visually-hidden">Sidebars examples</h1>
                    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
                        {% for ccategory in categories %}
                            {% if category == ccategory %}
                                <b><a class="nav-link" href="{% url 'feedbacker:'|add:ccategory %}">{{ ccategory|capfirst }}</a></b>
                            {%  else %}
                                <a class="nav-link" href="{% url 'feedbacker:'|add:ccategory %}">{{ ccategory|capfirst }}</a>
                            {% endif %}
                        {%  endfor %}
                    </div>
                    <div class="b-example-divider"></div>
                    <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
                        {% block contents %}
                            {{ lipsum }}
                        {% endblock %}
                    </div>
                {% endblock %}
            <!--/div-->

        <!--/div-->

    </div>
</body>
<script>
    function delayedClose() {
        setTimeout(function() {
            document.getElementById('closeButton').click();
            document.getElementById('name').value = '';
            const description = document.getElementById('description');
            if (description!==null) {
                description.value = '';
            }
            window.location.reload();
        }, 1000); // Delay of 1 second
    }
</script>
</html>

feedbacker/templates/feedbacker/base_aligned.html
{% extends "demo_django_task/base.html" %}
{% block breadcrumbs %}{% endblock %}
{% block coltype %}colM{% endblock %}
{% block content_div_id %}{% endblock %}
{% load i18n static bootstrap5 %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/sidebars.css' %}" />
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>
    <script src="https://kit.fontawesome.com/666340fc51.js" crossorigin="anonymous"></script>
{% endblock %}
{% block responsive %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% endblock %}
{% block content %}
    <main>
        <h1 class="visually-hidden">Sidebars examples</h1>
        <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
            {% for ccategory in categories %}
                {% if category == ccategory %}
                    <b><a class="nav-link" href="{% url 'feedbacker:'|add:ccategory %}">{{ ccategory|capfirst }}</a></b>
                {%  else %}
                    <a class="nav-link" href="{% url 'feedbacker:'|add:ccategory %}">{{ ccategory|capfirst }}</a>
                {% endif %}
            {%  endfor %}
        </div>
        <div class="b-example-divider"></div>
        <div class="flex-column flex-shrink-0 p-3 bg-light" style="width:80%">
            {% block contents %}
                {{ lipsum }}
            {% endblock %}
        </div>
    </main>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        function delayedClose() {
            setTimeout(function() {
                document.getElementById('closeButton').click();
                document.getElementById('name').value = '';
                const description = document.getElementById('description');
                if (description!==null) {
                    description.value = '';
                }
                window.location.reload();
            }, 1000); // Delay of 1 second
        }
    </script>
{% endblock %}

feedbacker/templates/feedbacker/confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete the {{ entity }} "{{ object.name }}"?</p>
    <input type="submit" value="Confirm">
</form>

feedbacker/templates/feedbacker/edit_form.html
{% extends "feedbacker/base_aligned.html" %}

{% block contents %}
  <h1>{{ title }}</h1>
  <form method="post">
    {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
    <button type="submit">Save</button>
  </form>
{% endblock %}

feedbacker/templates/feedbacker/feature_confirm_delete.html
<form method="post">{% csrf_token %}
<p>Are you sure you want to delete the feature "{{ object.name }}"?</p>
    <input type="submit" value="Confirm">
</form>

feedbacker/templates/feedbacker/feature_form.html
{% extends "feedbacker/base.html" %}

{% block contents %}
  <h1>{{ title }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

feedbacker/templates/feedbacker/features.html
{% extends "feedbacker/base_aligned.html" %}
{% block title %}Features list{% endblock %}
{% block contents %}
    <h1>Features list</h1>
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#myModal">Create feature</button>
    <table class="table table-striped">
    <thead>
        <td>Feature</td><td>Description</td><td>Commands</td>
    </thead>
    <tbody>
        {% for feature in object_list %}
            <tr>
                <td>
                    {{ feature.name }}
                </td><td>
                    {{ feature.description }}
                </td><td>
                    <a href="{% url 'feedbacker:feature_edit' feature.id %}">(edit)</a>
                    <a href="{% url 'feedbacker:feature_delete' feature.id %}">(delete)</a>
                </td>
            </tr>
        {% empty %}
            <tr><td>No features registered yet</td></tr>
        {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create feature</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <div class="modal-body">
                    <table>
                        <tr>
                            <td><label for="name">Name:</label></td>
                            <td><input type="text" id="name" name="name"/></td>
                        </tr>
                        <tr>
                            <td><label for="description">Description:</label></td>
                            <td><textarea id="description" name="description"></textarea></td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer submit-row">
                    <span id="submit-result"></span>
                    <button type="submit" class="btn btn-primary" hx-post="{% url 'feedbacker:feature_create' %}" hx-swap="innerHTML" hx-target="#submit-result">Create</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="closeButton">Close</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

feedbacker/templates/feedbacker/index.html
{% extends "feedbacker/base_aligned.html" %}
{% block title %}Feedback handler{% endblock %}
{% block contents %}
    <h1>Feature tracker</h1>
    <li><a href="{% url "feedbacker:features" %}">Features</a></li>
    <li><a href="{% url "feedbacker:tags" %}">Tags</a></li>
    <li><a href="{% url "feedbacker:users" %}">Users</a></li>
{% endblock %}

feedbacker/templates/feedbacker/tags.html
{% extends "feedbacker/base_aligned.html" %}
{% block title %}Tags list{% endblock %}
{% block contents %}
    <h1>Tags list</h1>
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#myModal">Create tag</button>
    <table class="table table-striped">
    <thead>
        <td>Tag</td><td>Commands</td>
    </thead>
    <tbody>
        {% for tag in object_list %}
            <tr>
                <td>
                    {{ tag.name }}
                </td><td>
                    <a href="{% url 'feedbacker:tag_edit' tag.id %}">(edit)</a>
                    <a href="{% url 'feedbacker:tag_delete' tag.id %}">(delete)</a>
                </td>
            </tr>
        {% empty %}
            <tr><td>No tags registered yet</td></tr>
        {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create tag</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <div class="modal-body">
                    <table>
                        <tr>
                            <td><label for="name">Name:</label></td>
                            <td><input type="text" id="name" name="name"/></td>
                        </tr>
                        <!--tr>
                            <td><label for="description">Description:</label></td>
                            <td><textarea id="description" name="description"></textarea></td>
                        </tr-->
                    </table>
                </div>
                <div class="modal-footer submit-row">
                    <span id="submit-result"></span>
                    <button type="submit" class="btn btn-primary" hx-post="{% url 'feedbacker:tag_create' %}" hx-swap="innerHTML" hx-target="#submit-result">Create</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="closeButton">Close</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

feedbacker/templates/feedbacker/users.html
{% extends "feedbacker/base.html" %}
{% block title %}Users list{% endblock %}
{% block contents %}
    <h1>Users list</h1>
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#myModal">Create user</button>
    <table class="table table-striped">
    <thead>
        <td>User</td><td>Commands</td>
    </thead>
    <tbody>
        {% for user in object_list %}
            <tr>
                <td>
                    {{ user.name }}
                </td><td>
                    <a href="{% url 'feedbacker:user_edit' user.id %}">(edit)</a>
                    <a href="{% url 'feedbacker:user_delete' user.id %}">(delete)</a>
                </td>
            </tr>
        {% empty %}
            <tr><td>No users registered yet</td></tr>
        {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create user</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <div class="modal-body">
                    <table>
                        <tr>
                            <td><label for="name">Name:</label></td>
                            <td><input type="text" id="name" name="name"/></td>
                        </tr>
                        <!--tr>
                            <td><label for="description">Description:</label></td>
                            <td><textarea id="description" name="description"></textarea></td>
                        </tr-->
                    </table>
                </div>
                <div class="modal-footer submit-row">
                    <span id="submit-result"></span>
                    <button type="submit" class="btn btn-primary" hx-post="{% url 'feedbacker:user_create' %}" hx-swap="innerHTML" hx-target="#submit-result">Create</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="closeButton">Close</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/demo_django_task/base.html
{% load i18n static bootstrap5 %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- change that for the own favicon -->
    <link rel="icon" href="{% static "img/logo.jpg" %}">
    <!-- getbootstrap.com template. check it out and merge into the own CSS file. -->
    <!--link href="https://getbootstrap.com/docs/4.0/examples/pricing/pricing.css" rel="stylesheet"-->
    {% bootstrap_css %}
    <!-- Project CSSs-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- CSS only -->
    <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"-->
    {#% bootstrap_css %#}
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
    {#% if not is_popup and is_nav_sidebar_enabled %#}
    {# <link rel="stylesheet" type="text/css" href="{% static "admin/css/nav_sidebar.css" %}"> #}
    {# <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script> #}
    {#% endif %#}
    {% block extrastyle %}{% endblock %}
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
    {% block extrahead %}{% endblock %}
    {% block responsive %}
        <!--meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"-->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
        {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
    {% endblock %}
  {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>

<body class="{#% if is_popup %}popup {% endif %#}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <script src="https://kit.fontawesome.com/666340fc51.js" crossorigin="anonymous"></script>

    <!-- Container -->
    <!--div id="_container"-->

        {% if not is_popup %}
        <!-- Header -->
        <div id="_header">
            <div id="_branding">
            {% block branding %}
                <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
                    <h5 class="my-0 mr-md-auto font-weight-normal" style="font-size: 14px"><a href="{% url 'index' %}">{{ page_title }}</a></h5>
                    <a class="p-2 text-dark" href="{% url 'index' %}">Home</a>
                    {% if user and user.is_active %}
                        Hello, {{ user }}!<a class="p-2 text-dark" href="{% url 'admin:index' %}">Administrate</a>
                    {% else %}
                        <a class="p-2 text-dark" href="{% url 'admin:login' %}">Log in</a>
                    {% endif %}
                </div>

            {% endblock %}
            </div>
            {% block usertools %}
            {% if has_permission %}
            <div id="user-tools">
                {% block welcome-msg %}
                    {% translate 'Welcome,' %}
                    <strong>{% firstof user.get_short_name user.get_username %}</strong>.
                {% endblock %}
                {% block userlinks %}
                    {% if site_url %}
                        <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                    {% endif %}
                    {% if user.is_active and user.is_staff %}
                        {% url 'django-admindocs-docroot' as docsroot %}
                        {% if docsroot %}
                            <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
                        {% endif %}
                    {% endif %}
                    {% if user.has_usable_password %}
                    <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
                    {% endif %}
                    <a href="{% url 'admin:logout' %}">{% translate 'Log out' %}</a>
                {% endblock %}
            </div>
            {% endif %}
            {% endblock %}
            {% block nav-global %}{% endblock %}
        </div>
        <!-- END Header -->
        {% block breadcrumbs %}
        <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
        {% if title %} &rsaquo; {{ title }}{% endif %}
        </div>
        {% endblock %}
        {% endif %}

        <div class="main shifted" id="main">
          {% if not is_popup and is_nav_sidebar_enabled %}
            {% block nav-sidebar %}
              {% include "admin/nav_sidebar.html" %}
            {% endblock %}
          {% endif %}
          <!--div class="content" id="content"-->
            {% block messages %}
              {% if messages %}
                <ul class="messagelist">{% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                {% endfor %}</ul>
              {% endif %}
            {% endblock messages %}
            <!-- Content -->
            <div id="{% block content_div_id %}content{% endblock %}" class="{% block coltype %}colM{% endblock %}">
              {% block pretitle %}{% endblock %}
              {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
              {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock %}
              {% block content %}
                {% block object-tools %}{% endblock %}
                {{ content }}
              {% endblock %}
              {% block sidebar %}{% endblock %}
              <br class="clear">
            </div>
            <!-- END Content -->
            {% block footer %}<div id="footer"></div>{% endblock %}
          <!--/div-->
        </div>
    <!--/div-->
    <!-- END Container -->
    {% block scripts %}
        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {#% bootstrap_javascript %#}
    {% endblock %}
</body>
</html>